version: '3.7'
services:

  db:
    image: postgres:15
    env_file:
      - .env
    container_name:
      mohostan_pg
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
    container_name:
      mohostan
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - ./static:/app/static
